### ISSUE TITLE
Developing custom UI Design in Cumulocity 

### ISSUE THREAD

**Issue by babupca** [dwiyatci/cumulocity-smart-apps-webpack#3]
Hi Dwiyatci,

I'm working from Aalen, Germany currently and I saw in your smart apps comments, you said 

 **_"but I'd still recommend you to develop plugins as it offers more out-of-the-box features and more convenient for newbs"_**

For the couple of weeks, we are working on creating custom cumulocity based applications. but we can not able to achieve it, because cumulocity does not give much options to modify the UI or we might miss some thing or we don't have enough documentation.

What we are trying to achieve ?
1. We are creating the application (fully custom UI Design), which should be hosted in cumulocity
2. We are going to have sensor data from a very big location, and update UI
3. Creating the cumulocity widgets in the plugins view, and not in the cockpit
3. We tried to modify the UI of cumulocity using brand plugins, but we could not able to do it. Only we can change the color using less variables & change the logo
4. Finally to do fully custom SPA in cumulocity, do we have to use only angular SDK

In order to create the fully functional custom UI design on our choice and hosted in the cumulocity which consumes service from cumulocity in real time. Please give you suggestions if you have any ?

Since i saw that you are from cumulocity Product development team, i wanted to ask you these questions.

Please ignore if you don't have answers.

Thanks
Babu Arumugam

**Comment by dwiyatci** [comment]
Hi @babupca,

there are basically at least 3 paths which you can take in order to create an own (custom) application on top of Cumulocity:

1. **Plugin-based own application**: create an AngularJS application from scratch by [importing bare minimum set of built-in plugins to make the Cumulocity app shell](http://cumulocity.com/guides/web/introduction/#configure-the-application-manifest) (usually only the branding plugin) and add more your own custom plugins from there by making use of reusable services, directives, and components from [Cumulocity AngularJS SDK](http://resources.cumulocity.com/documentation/jssdk/latest/#/api) and [Cumulocity UI Style Guide](http://styleguide.cumulocity.com/). 
Example repos:
  - https://github.com/dwiyatci/cumulocity-hello-plugin-modular
  - https://github.com/dwiyatci/cumulocity-hellowidget-plugin

2. **Extended existing default own application**: like plugin-based own application, but extending an existing default app (Cockpit, Device management, or Administration) by adding own plugins, and removing and/or replacing the imported built-in plugins which build the existing app. 
Example repos:
  - https://github.com/dwiyatci/cumulocity-kitchensink
  - https://github.com/dwiyatci/cumulocity-unicornify-widget

3. **Fully-Customised own application**: create a frontend framework-agnostic application which is not bound to Cumulocity plugin system and make use of [Cumulocity REST API](https://app.getpostman.com/run-collection/7c7d00719ab238097686) instead. Choose our own stack and module bundler. Either [The framework-agnostic JavaScript client library](https://www.npmjs.com/package/@c8y/client) (for Angular 2+, React, Vue, etc.) or [Web SDK for AngularJS](https://github.com/Cumulocity/cumulocity-clients-javascript) (for AngularJS) are likely to be used. 
Example repos:
  - https://github.com/dwiyatci/c8y-angular-polymer-boilerplate
  - [this repo](https://github.com/dwiyatci/cumulocity-smart-apps-webpack).

While # 3 offers more flexibility and customisability, it doesn't offer much reusable services and components at the moment as # 1 or # 2 does (i.e. you have to do the design and develop almost everything from scratch but you're not bound to the limitation of the branding plugin and AngularJS).

I'm going to close this issue since we have pretty much deviated from of what's supposed to be considered as this repo's issue, and just to be clear here, I'm not a Core SDK/API developer of Cumulocity (I'm just using the Core SDK/API to create custom modules/apps). Should you have further queries, please direct them to support@cumulocity.com.

HTH,
Glenn

**Comment by babupca** [comment]
Thanks for your time & information.
